pipeline {
    agent any

    tools {
        python 'Python 3'  // Assumes you have configured this in Jenkins (ShiningPanda)
    }

    stages {
        stage('Clone repository') {
            steps {
                git credentialsId: 'github-credentials',
                    url: 'https://github.com/your-username/alx-backend-python.git',
                    branch: 'main'
            }
        }

        stage('Set up virtualenv & install dependencies') {
            steps {
                sh '''
                cd messaging_app
                python3 -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                cd messaging_app
                source venv/bin/activate
                pytest --junitxml=test-results.xml
                '''
            }
        }

        stage('Archive Test Report') {
            steps {
                junit 'messaging_app/test-results.xml'
            }
        }
    }
}
