# Generated by Django 5.2.1 on 2025-06-18 11:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(default=uuid.UUID('d740e7bd-381d-499e-99cc-f97177679ce5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('1b391179-538e-456e-8b63-fda6bf0019df'), editable=False, primary_key=True, serialize=False),
        ),
    ]
