# Generated by Django 5.2.1 on 2025-06-18 11:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(default=uuid.UUID('f7cb7f81-eed7-4c7c-8aaa-74570e5b850f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('ec658e8d-fd4b-4223-936d-da0382439eac'), editable=False, primary_key=True, serialize=False),
        ),
    ]
