# Generated by Django 5.2.1 on 2025-06-18 12:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_id',
            field=models.UUIDField(default=uuid.UUID('31c38150-0960-4a1d-a311-2bd4314c115c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('5cab8e5c-4348-42ac-b97b-a19b6eca6971'), editable=False, primary_key=True, serialize=False),
        ),
    ]
