apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
    version: blue  # Initial target is "blue"; change to "green" for switch
  ports:
  - port: 8000
    targetPort: 8000
